apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-echo.fullname" . }}
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
    {{- if .Values.https.enabled }}
      targetPort: https
      name: https
    {{ else }}
      targetPort: http
      name: http
    {{- end }}
  selector:
    {{- include "http-echo.selectorLabels" . | nindent 4 }}
